### ISSUE TITLE
Atom containing `?` giving compilation error

### ISSUE THREAD

**Issue by rhnonose** [meyercm/shorter_maps#10]
When I use an atom with a trailing `?` it gives a compilation warning.
Here's the output in IEx:
```
iex(2)> ~M{a?} = %{a?: true}
** (CompileError) iex:2: expected key-value pairs in a map, got: a?
    (stdlib) lists.erl:1263: :lists.foldl/3
    (shorter_maps) expanding macro: ShorterMaps.sigil_M/2
    iex:2: (file)
```
Is there a subset of characters that are not supported?
My current version is the latest on hex, `2.2.3`

**Comment by meyercm** [comment]
I've just published 2.2.4, which should correct this issue.  Thanks for the good bug report!
