### ISSUE TITLE
Consider modifieries

### ISSUE THREAD

**Issue by andrejsm** [meyercm/shorter_maps#3]
Have you considered to use modifiers instead of having lower and upper case sigils? Like Elixir's [Sigil_W](https://hexdocs.pm/elixir/1.3.3/Kernel.html#sigil_W/2) for example.
ShorterMaps could have `a` and `s`. Where `a` stands for atoms (default) and `s` for strings.

Like this:
```elixir
~M{a, b, c}
# %{a: a, b: b, c: c}

~M{a, b, c}s
# %{"a" => a, "b" => b, "c" => c}
```

I'm suggesting this as most of Elixir's sigils, except Sigil_D, Sigil_T and Sigil_N, have lower case sigil to output interpolated and escaped characters.

**Comment by andrejsm** [comment]
Ahh, never mind, found support for modifiers already exists [https://hexdocs.pm/shorter_maps/ShorterMaps.html#sigil_M/2-modifiers](https://hexdocs.pm/shorter_maps/ShorterMaps.html#sigil_M/2-modifiers).
Readme on Github does not list support for modifiers, though.

**Comment by meyercm** [comment]
Thanks for the careful look;  the omission in the README documentation is worth fixing.

Out of curiosity, do you commonly use `~W` in some places, and intentionally use `~w` in others?  If so, what use case causes you to differentiate?

**Comment by andrejsm** [comment]
I use lower case `~w` only, but never had to use interpolation, though.

Did some grepping and found out that mostly I've used `~w` with `get_in/2`:
```elixir
foo = get_in(bar, ~w(foo bar baz))
```
With this avoiding to write `["foo", "bar", "baz"]`.
