### ISSUE TITLE
Is it possible to use `~M` "recursively"?

### ISSUE THREAD

**Issue by mikestok** [meyercm/shorter_maps#4]
Is there any way to use `ShorterMaps` to go down multiple levels similar to:

```
iex(1)> %{foo: %{bar: bar}, baz: baz} = %{foo: %{bar: "plugh"}, baz: "xyyzy"}
%{baz: "xyyzy", foo: %{bar: "plugh"}}
iex(2)> [bar, baz]
["plugh", "xyyzy"]
```

This works...

```
iex(1)> import ShorterMaps
ShorterMaps
iex(2)> ~M{foo, baz} = %{foo: %{bar: "plugh"}, baz: "xyyzy"}
%{baz: "xyyzy", foo: %{bar: "plugh"}}
iex(3)> [foo, baz]
[%{bar: "plugh"}, "xyyzy"]
```

but I can't figure out the syntax to be able to pull `"plugh"` out and assign it to `baz` in one step. Should I be able to do this using `ShorterMaps`?

**Comment by meyercm** [comment]
In short, no.

The current syntax only supports a single level of expansion.  The real difficulty in creating what you want is that ~M is expanding as a sigil macro, which must accept and parse a string.  Sadly, it seems that sigil parsing stops at the first occurrence of the closing brace:

```elixir
#             v=== Parsing seems to stop here
~M{foo: ~M{bar}, baz}
```  
To really see how Elixir treats a sigil, paste this simple module into `iex`:

```elixir
defmodule Test do
  defmacro sigil_x(str, opts) do
    quote do
      [unquote(str), unquote(opts)]
    end
  end
end
```
```elixir
iex> import Test
Test
iex> ~x{a}
["a", []]
iex> ~x{a: {}}
** (SyntaxError) iex:13: unexpected token: }

iex> ~x{a: ()}
["a: ()", []]
```

This test indicates that even if the recursion is implemented, the syntax will be hideous, e.g.
```elixir
# legal to use any of these: //  ||  ""  ''  ()  []  {}  <> to wrap a sigil:
~M{foo: ~M(bar), baz}

```

What you are really looking for is first-class language support for the syntax, and there's an old discussion where José recommends Sigils for the purpose - I imagine his mind is made up.

**Comment by mikestok** [comment]
I appreciate the informative reply. Thank you :-)
